package sarie.bridge

// Generated by plugin/scripts/generate-fingerprints.sh: the okhttp versions pinned in
// RecipeRegistry and structurally verified against the registered guard (see
// plugin/recipe-verification-report.md). Do not hand-edit; rerun the script.
internal val VerifiedOkHttpVersions: Set<String> = setOf(
    "5.4.0",
    "5.5.0",
)
