package dev.okhttpcronet.plugin

import java.security.MessageDigest

object Fingerprint {

    fun sha256Hex(bytes: ByteArray): String =
        MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

    // Generated by plugin-build/scripts/generate-fingerprints.sh from the pinned okhttp 5.5.0
    // artifacts (see THIRD_PARTY.md "Golden bytecode artifacts"). Do not hand-edit.
    const val OKHTTP_ANDROID_CLASS_SHA256 = "bd324e22d23fd4a71896d116a745d37bdaa36a14e4a162cb808ac7b524c5e527"
    const val OKHTTP_JVM_CLASS_SHA256 = "bd324e22d23fd4a71896d116a745d37bdaa36a14e4a162cb808ac7b524c5e527"
}
