package dev.okhttpcronet.plugin

// Generated by plugin-build/scripts/generate-fingerprints.sh from the pinned okhttp
// artifacts (see THIRD_PARTY.md "Golden bytecode artifacts"). Do not hand-edit.
object GoldenFingerprints {
    val OKHTTP_ANDROID_5_5_0 = "bd324e22d23fd4a71896d116a745d37bdaa36a14e4a162cb808ac7b524c5e527"
    val OKHTTP_JVM_5_5_0 = "bd324e22d23fd4a71896d116a745d37bdaa36a14e4a162cb808ac7b524c5e527"
}
