package sarie.plugin

// Generated by plugin/scripts/generate-fingerprints.sh from the pinned okhttp
// artifacts (see plugin/recipe-verification-report.md). Do not hand-edit.
object GoldenFingerprints {
    val OKHTTP_ANDROID_5_0_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_JVM_5_0_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_ANDROID_5_1_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_JVM_5_1_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_ANDROID_5_2_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_JVM_5_2_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_ANDROID_5_2_1 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_JVM_5_2_1 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_ANDROID_5_2_2 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_JVM_5_2_2 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_ANDROID_5_2_3 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_JVM_5_2_3 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_ANDROID_5_3_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_JVM_5_3_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_ANDROID_5_3_1 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_JVM_5_3_1 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_ANDROID_5_3_2 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_JVM_5_3_2 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val OKHTTP_ANDROID_5_4_0 = "bd324e22d23fd4a71896d116a745d37bdaa36a14e4a162cb808ac7b524c5e527"
    val OKHTTP_JVM_5_4_0 = "bd324e22d23fd4a71896d116a745d37bdaa36a14e4a162cb808ac7b524c5e527"
    val OKHTTP_ANDROID_5_5_0 = "bd324e22d23fd4a71896d116a745d37bdaa36a14e4a162cb808ac7b524c5e527"
    val OKHTTP_JVM_5_5_0 = "bd324e22d23fd4a71896d116a745d37bdaa36a14e4a162cb808ac7b524c5e527"

    fun fingerprintsFor(version: String): Map<Variant, String>? = when (version) {
        "5.0.0" -> mapOf(Variant.ANDROID to OKHTTP_ANDROID_5_0_0, Variant.JVM to OKHTTP_JVM_5_0_0)
        "5.1.0" -> mapOf(Variant.ANDROID to OKHTTP_ANDROID_5_1_0, Variant.JVM to OKHTTP_JVM_5_1_0)
        "5.2.0" -> mapOf(Variant.ANDROID to OKHTTP_ANDROID_5_2_0, Variant.JVM to OKHTTP_JVM_5_2_0)
        "5.2.1" -> mapOf(Variant.ANDROID to OKHTTP_ANDROID_5_2_1, Variant.JVM to OKHTTP_JVM_5_2_1)
        "5.2.2" -> mapOf(Variant.ANDROID to OKHTTP_ANDROID_5_2_2, Variant.JVM to OKHTTP_JVM_5_2_2)
        "5.2.3" -> mapOf(Variant.ANDROID to OKHTTP_ANDROID_5_2_3, Variant.JVM to OKHTTP_JVM_5_2_3)
        "5.3.0" -> mapOf(Variant.ANDROID to OKHTTP_ANDROID_5_3_0, Variant.JVM to OKHTTP_JVM_5_3_0)
        "5.3.1" -> mapOf(Variant.ANDROID to OKHTTP_ANDROID_5_3_1, Variant.JVM to OKHTTP_JVM_5_3_1)
        "5.3.2" -> mapOf(Variant.ANDROID to OKHTTP_ANDROID_5_3_2, Variant.JVM to OKHTTP_JVM_5_3_2)
        "5.4.0" -> mapOf(Variant.ANDROID to OKHTTP_ANDROID_5_4_0, Variant.JVM to OKHTTP_JVM_5_4_0)
        "5.5.0" -> mapOf(Variant.ANDROID to OKHTTP_ANDROID_5_5_0, Variant.JVM to OKHTTP_JVM_5_5_0)
        else -> null
    }
}
