package sarie.plugin

// Generated by plugin/scripts/generate-fingerprints.sh from the pinned okhttp
// artifacts (see plugin/recipe-verification-report.md). Do not hand-edit.
object GoldenFingerprints {
    val CONNECT_INTERCEPTOR_ANDROID_5_0_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_JVM_5_0_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_ANDROID_5_1_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_JVM_5_1_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_ANDROID_5_2_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_JVM_5_2_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_ANDROID_5_2_1 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_JVM_5_2_1 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_ANDROID_5_2_2 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_JVM_5_2_2 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_ANDROID_5_2_3 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_JVM_5_2_3 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_ANDROID_5_3_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_JVM_5_3_0 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_ANDROID_5_3_1 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_JVM_5_3_1 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_ANDROID_5_3_2 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_JVM_5_3_2 = "e0840705f2836f0c9f220f8b256a56a2b2c4562bfb171d1dae1875443e95781e"
    val CONNECT_INTERCEPTOR_ANDROID_5_4_0 = "bd324e22d23fd4a71896d116a745d37bdaa36a14e4a162cb808ac7b524c5e527"
    val CONNECT_INTERCEPTOR_JVM_5_4_0 = "bd324e22d23fd4a71896d116a745d37bdaa36a14e4a162cb808ac7b524c5e527"
    val CALL_SERVER_INTERCEPTOR_ANDROID_5_4_0 = "5ac4bd374d3cc4149d270c7d908d7af89fe958e653cf21921ac9f8c3504b4026"
    val CALL_SERVER_INTERCEPTOR_JVM_5_4_0 = "5ac4bd374d3cc4149d270c7d908d7af89fe958e653cf21921ac9f8c3504b4026"
    val CONNECT_INTERCEPTOR_ANDROID_5_5_0 = "bd324e22d23fd4a71896d116a745d37bdaa36a14e4a162cb808ac7b524c5e527"
    val CONNECT_INTERCEPTOR_JVM_5_5_0 = "bd324e22d23fd4a71896d116a745d37bdaa36a14e4a162cb808ac7b524c5e527"
    val CALL_SERVER_INTERCEPTOR_ANDROID_5_5_0 = "5ac4bd374d3cc4149d270c7d908d7af89fe958e653cf21921ac9f8c3504b4026"
    val CALL_SERVER_INTERCEPTOR_JVM_5_5_0 = "5ac4bd374d3cc4149d270c7d908d7af89fe958e653cf21921ac9f8c3504b4026"

    fun fingerprintsFor(version: String): Map<InstrumentTarget, Map<Variant, String>>? = when (version) {
        "5.0.0" -> mapOf(
            InstrumentTarget.CONNECT_INTERCEPTOR to mapOf(
                Variant.ANDROID to CONNECT_INTERCEPTOR_ANDROID_5_0_0,
                Variant.JVM to CONNECT_INTERCEPTOR_JVM_5_0_0,
            ),
        )
        "5.1.0" -> mapOf(
            InstrumentTarget.CONNECT_INTERCEPTOR to mapOf(
                Variant.ANDROID to CONNECT_INTERCEPTOR_ANDROID_5_1_0,
                Variant.JVM to CONNECT_INTERCEPTOR_JVM_5_1_0,
            ),
        )
        "5.2.0" -> mapOf(
            InstrumentTarget.CONNECT_INTERCEPTOR to mapOf(
                Variant.ANDROID to CONNECT_INTERCEPTOR_ANDROID_5_2_0,
                Variant.JVM to CONNECT_INTERCEPTOR_JVM_5_2_0,
            ),
        )
        "5.2.1" -> mapOf(
            InstrumentTarget.CONNECT_INTERCEPTOR to mapOf(
                Variant.ANDROID to CONNECT_INTERCEPTOR_ANDROID_5_2_1,
                Variant.JVM to CONNECT_INTERCEPTOR_JVM_5_2_1,
            ),
        )
        "5.2.2" -> mapOf(
            InstrumentTarget.CONNECT_INTERCEPTOR to mapOf(
                Variant.ANDROID to CONNECT_INTERCEPTOR_ANDROID_5_2_2,
                Variant.JVM to CONNECT_INTERCEPTOR_JVM_5_2_2,
            ),
        )
        "5.2.3" -> mapOf(
            InstrumentTarget.CONNECT_INTERCEPTOR to mapOf(
                Variant.ANDROID to CONNECT_INTERCEPTOR_ANDROID_5_2_3,
                Variant.JVM to CONNECT_INTERCEPTOR_JVM_5_2_3,
            ),
        )
        "5.3.0" -> mapOf(
            InstrumentTarget.CONNECT_INTERCEPTOR to mapOf(
                Variant.ANDROID to CONNECT_INTERCEPTOR_ANDROID_5_3_0,
                Variant.JVM to CONNECT_INTERCEPTOR_JVM_5_3_0,
            ),
        )
        "5.3.1" -> mapOf(
            InstrumentTarget.CONNECT_INTERCEPTOR to mapOf(
                Variant.ANDROID to CONNECT_INTERCEPTOR_ANDROID_5_3_1,
                Variant.JVM to CONNECT_INTERCEPTOR_JVM_5_3_1,
            ),
        )
        "5.3.2" -> mapOf(
            InstrumentTarget.CONNECT_INTERCEPTOR to mapOf(
                Variant.ANDROID to CONNECT_INTERCEPTOR_ANDROID_5_3_2,
                Variant.JVM to CONNECT_INTERCEPTOR_JVM_5_3_2,
            ),
        )
        "5.4.0" -> mapOf(
            InstrumentTarget.CONNECT_INTERCEPTOR to mapOf(
                Variant.ANDROID to CONNECT_INTERCEPTOR_ANDROID_5_4_0,
                Variant.JVM to CONNECT_INTERCEPTOR_JVM_5_4_0,
            ),
            InstrumentTarget.CALL_SERVER_INTERCEPTOR to mapOf(
                Variant.ANDROID to CALL_SERVER_INTERCEPTOR_ANDROID_5_4_0,
                Variant.JVM to CALL_SERVER_INTERCEPTOR_JVM_5_4_0,
            ),
        )
        "5.5.0" -> mapOf(
            InstrumentTarget.CONNECT_INTERCEPTOR to mapOf(
                Variant.ANDROID to CONNECT_INTERCEPTOR_ANDROID_5_5_0,
                Variant.JVM to CONNECT_INTERCEPTOR_JVM_5_5_0,
            ),
            InstrumentTarget.CALL_SERVER_INTERCEPTOR to mapOf(
                Variant.ANDROID to CALL_SERVER_INTERCEPTOR_ANDROID_5_5_0,
                Variant.JVM to CALL_SERVER_INTERCEPTOR_JVM_5_5_0,
            ),
        )
        else -> null
    }
}
